Repository opendilab/DI-engine, pull requests merged in 2021-12, with the labels that each got.

#134 fix(crb): add unpickling error catch for sync env manager
  ding/envs/env_manager/subprocess_env_manager.py
Labels: enhancement

#135 feature(zjow): add feature of profile in ding
  ding/entry/cli.py
  ding/entry/main_sac.py
  ding/utils/__init__.py
  ding/utils/profiler_helper.py
  ding/utils/tests/test_profiler_helper.py
  setup.py
Labels: enhancement

#137 fix(crb): fix subenvmanager reset bug
  ding/envs/env_manager/subprocess_env_manager.py
Labels: bug

#112 feature(wyh):add masac algorithms
  ding/entry/tests/test_serial_entry.py
  ding/model/template/__init__.py
  ding/model/template/maqac.py
  ding/model/template/mavac.py
  ding/model/template/qac.py
  ding/model/template/tests/test_mavac.py
  ding/model/template/tests/test_qac.py
  ding/policy/__init__.py
  ding/policy/command_mode_policy_instance.py
  ding/policy/ppo.py
  ding/policy/sac.py
  ding/rl_utils/__init__.py
  ding/rl_utils/td.py
  dizoo/box2d/lunarlander/config/lunarlander_sac_config.py
  dizoo/classic_control/cartpole/config/cartpole_sac_config.py
  dizoo/smac/config/smac_3m_masac_config.py
  dizoo/smac/config/smac_3s5z_masac_config.py
  dizoo/smac/config/smac_5m6m_masac_config.py
  dizoo/smac/config/smac_MMM2_masac_config.py
  dizoo/smac/config/smac_MMM_masac_config.py
  dizoo/smac/envs/smac_env.py
Labels: serial, algo

#148 add conda auto release
  .github/workflows/release_conda.yml
  conda/conda_build_config.yaml
  conda/meta.yaml
Labels: enhancement

#145 feature(nyz): add delay reward mujoco env
  dizoo/mujoco/envs/mujoco_env.py
  dizoo/mujoco/envs/test_mujoco_env.py
Labels: env

#149 feature(nyp):add R2d2 comments
  ding/model/template/q_learning.py
  ding/model/wrapper/model_wrappers.py
  ding/policy/r2d2.py
  ding/utils/data/collate_fn.py
  ding/worker/collector/sample_serial_collector.py
  dizoo/classic_control/cartpole/config/cartpole_r2d2_config.py
Labels: algo

#139 feature(lk): fix port conflict
  dizoo/gym_soccer/config/gym_soccer_pdqn_config.py
  dizoo/gym_soccer/envs/gym_soccer_env.py
Labels: bug, env

#142 feature(xjx): new main framework
  ding/entry/cli.py
  ding/entry/main.py
  ding/framework/__init__.py
  ding/framework/context.py
  ding/framework/parallel.py
  ding/framework/task.py
  ding/framework/tests/test_context.py
  ding/framework/tests/test_parallel.py
  ding/framework/tests/test_task.py
  ding/framework/tests/test_wrapper.py
  ding/framework/wrapper/__init__.py
  ding/framework/wrapper/step_timer.py
  ding/utils/__init__.py
  ding/utils/profiler_helper.py
  ding/utils/tests/test_profiler_helper.py
  ding/worker/learner/base_learner.py
  setup.py
Labels: enhancement

#146 Env(wyh):multi agent mujoco environment
  README.md
  ding/model/template/__init__.py
  ding/model/template/maqac.py
  ding/policy/cql.py
  ding/policy/sac.py
  ding/rl_utils/td.py
  ding/rl_utils/tests/test_td.py
  dizoo/multiagent_mujoco/README.md
  dizoo/multiagent_mujoco/__init__.py
  dizoo/multiagent_mujoco/config/ant_masac_default_config.py
  dizoo/multiagent_mujoco/envs/__init__.py
  dizoo/multiagent_mujoco/envs/assets/.gitignore
  dizoo/multiagent_mujoco/envs/assets/__init__.py
  dizoo/multiagent_mujoco/envs/assets/coupled_half_cheetah.xml
  dizoo/multiagent_mujoco/envs/assets/manyagent_ant.xml
  dizoo/multiagent_mujoco/envs/assets/manyagent_ant.xml.template
  dizoo/multiagent_mujoco/envs/assets/manyagent_ant__stage1.xml
  dizoo/multiagent_mujoco/envs/assets/manyagent_swimmer.xml.template
  dizoo/multiagent_mujoco/envs/assets/manyagent_swimmer__bckp2.xml
  dizoo/multiagent_mujoco/envs/assets/manyagent_swimmer_bckp.xml
  dizoo/multiagent_mujoco/envs/coupled_half_cheetah.py
  dizoo/multiagent_mujoco/envs/manyagent_ant.py
  dizoo/multiagent_mujoco/envs/manyagent_swimmer.py
  dizoo/multiagent_mujoco/envs/mujoco_multi.py
  dizoo/multiagent_mujoco/envs/multi_mujoco_env.py
  dizoo/multiagent_mujoco/envs/multiagentenv.py
  dizoo/multiagent_mujoco/envs/obsk.py
Labels: env

#155 fix(nyz): fix doc generate bug with enum_tools
  .github/workflows/doc.yml
Labels: bug

#154 polish(pu):polish eps_greedy_multinomial_sample in model_wrappers and masac
  ding/model/wrapper/model_wrappers.py
  ding/policy/sac.py
Labels: algo

#156 feature(xjx): multiprocess tblogger, fix circular reference problem
  .gitignore
  ding/framework/context.py
  ding/framework/parallel.py
  ding/framework/task.py
  ding/framework/tests/test_parallel.py
  ding/framework/tests/test_task.py
  ding/framework/tests/test_wrapper.py
  ding/utils/__init__.py
  ding/utils/log_helper.py
  ding/utils/log_writer_helper.py
  ding/utils/tests/test_log_helper.py
  ding/utils/tests/test_log_writer_helper.py
Labels: enhancement

#160 feature(xjx): cli in new pipeline
  ding/entry/__init__.py
  ding/entry/cli_ditask.py
  ding/framework/parallel.py
  ding/framework/task.py
  setup.py
Labels: enhancement

#163 fix(xjx): change max step from float to int
  ding/framework/task.py
Labels: bug

#166 doc(xjx): add docs, wrap decorators
  ding/framework/parallel.py
  ding/framework/task.py
  ding/worker/buffer/buffer.py
Labels: test

#168 Fix deps mpire
  setup.py
Labels: bug

#169 feature(gg15): add gumbel softmax
  ding/torch_utils/network/__init__.py
  ding/torch_utils/network/gumbel_softmax.py
  ding/torch_utils/network/tests/test_gumbel_softmax.py
Labels: algo
