Repository opendilab/DI-engine, pull requests merged in 2021-09, with the labels that each got.

#22 League Metric
  ding/league/__init__.py
  ding/league/base_league.py
  ding/league/metric.py
  ding/league/one_vs_one_league.py
  ding/league/player.py
  ding/league/starcraft_player.py
  ding/league/tests/test_league_metric.py
  ding/league/tests/test_payoff.py
  ding/league/tests/test_player.py
  ding/worker/collector/one_vs_one_serial_evaluator.py
  dizoo/league_demo/demo_league.py
  dizoo/league_demo/game_env.py
  dizoo/league_demo/league_demo_ppo_config.py
  dizoo/league_demo/league_demo_ppo_main.py
  dizoo/league_demo/selfplay_demo_ppo_main.py
  setup.py
Labels: enhancement

#39 feature(zlx): Add tb in naive buffer; modify tb in advanced buffer
  ding/worker/replay_buffer/advanced_buffer.py
  ding/worker/replay_buffer/naive_buffer.py
  ding/worker/replay_buffer/utils.py
Labels: bug, enhancement

#44 enable user to use any model generated here
  ding/entry/cli.py
  ding/entry/serial_entry_sqil.py
  ding/entry/tests/test_serial_entry_algo.py
  ding/entry/tests/test_serial_entry_sqil.py
Labels: enhancement, algo

#45 add k8s launcher and di-orchestrator launcher
  .github/workflows/platform_test.yml
  .github/workflows/unit_test.yml
  ding/scripts/install-k8s-tools.sh
  ding/utils/__init__.py
  ding/utils/k8s_helper.py
  ding/utils/orchestrator_launcher.py
  ding/utils/tests/config/k8s-config.yaml
  ding/utils/tests/test_k8s_launcher.py
Labels: enhancement, parallel-dist

#49 [feature] add cartpole test running in k8s cluster
  .github/workflows/algo_test.yml
  ding/entry/tests/config/agconfig.yaml
  ding/entry/tests/config/dijob-cartpole.yaml
  ding/entry/tests/config/k8s-config.yaml
  ding/entry/tests/test_serial_entry_algo.py
  ding/utils/k8s_helper.py
  ding/utils/orchestrator_launcher.py
Labels: enhancement, parallel-dist

#54 fix(wyh):mappo nan bug and dict cannot unsqueeze
  ding/model/template/mappo.py
  ding/policy/ppo.py
Labels: bug

#38 feature(lk): add hyper-parameter scheduler module
  ding/utils/__init__.py
  ding/utils/scheduler_helper.py
  ding/utils/tests/test_scheduler_helper.py
  dizoo/league_demo/league_demo_ppo_config.py
  dizoo/league_demo/league_demo_ppo_main.py
Labels: enhancement

#53 fix(wyh):formatted config no eval bug
  ding/config/utils.py
  dizoo/classic_control/cartpole/config/cartpole_dqn_config.py
  dizoo/procgen/coinrun/entry/coinrun_dqn_config.py
Labels: bug

#52 fix(pu): fix r2d2 done slice bug and LSTM hidden state reset bug
  ding/entry/tests/test_serial_entry_algo.py
  ding/model/template/q_learning.py
  ding/policy/r2d2.py
  dizoo/box2d/lunarlander/config/lunarlander_r2d2_config.py
  dizoo/classic_control/cartpole/config/cartpole_r2d2_config.py
  dizoo/minigrid/config/minigrid_r2d2_config.py
  dizoo/pybullet/envs/pybullet_wrappers.py
Labels: bug, algo

#51 feature(crb): update multi discrete policy(dqn, ppo, rainbow)
  dizoo/common/policy/md_dqn.py
  dizoo/common/policy/md_ppo.py
  dizoo/common/policy/md_rainbow_dqn.py
Labels: enhancement, serial

#58 feature(davide): add BSuite environment wrapper
  README.md
  dizoo/bsuite/__init__.py
  dizoo/bsuite/bsuite.png
  dizoo/bsuite/config/__init__.py
  dizoo/bsuite/config/serial/bandit_noise/bandit_noise_0_dqn_config.py
  dizoo/bsuite/config/serial/cartpole_swingup/cartpole_swingup_0_dqn_config.py
  dizoo/bsuite/config/serial/memory_len/memory_len_0_dqn_config.py
  dizoo/bsuite/entry/__init__.py
  dizoo/bsuite/entry/cartpole_swingup/cartpole_swingup_0_dqn_main.py
  dizoo/bsuite/entry/memory_len/memory_len_0_dqn_main.py
  dizoo/bsuite/envs/__init__.py
  dizoo/bsuite/envs/bsuite_env.py
  dizoo/bsuite/envs/test_bsuite_env.py
  setup.py
Labels: env

#59 fix(wyh): plot function
  ding/utils/plot_helper.py
  ding/utils/tests/test_plot.py
  setup.py
Labels: enhancement

#62 feature(wyh):mappo and ippo win rate and time
  dizoo/smac/README.md
Labels: env

#69 fix(hansbug): fix spawn context problem in interaction unittest
  ding/interaction/tests/base/test_network.py
  ding/interaction/tests/interaction/bases.py
  ding/interaction/tests/interaction/test_errors.py
  ding/interaction/tests/interaction/test_simple.py
Labels: bug

#70 style(nyz): add docker deploy in github workflow
  .github/workflows/deploy.yml
Labels: enhancement

#71 fix(xjx): fix the catch statments that will never succeed in test net…
  ding/interaction/tests/base/test_network.py
  ding/interaction/tests/test_utils/stream.py
Labels: bug

#72 feature(crb): add multi-discrete ppo and off policy ppo
  dizoo/common/policy/md_ppo.py
Labels: serial, algo

#77 feature(nyz): move atari_py to ale-py; split base and env docker build
  .github/workflows/deploy.yml
  Dockerfile.base
  Dockerfile.env
  dizoo/atari/envs/__init__.py
  dizoo/atari/envs/atari_env.py
  dizoo/atari/envs/atari_multi_discrete_env.py
  dizoo/atari/envs/test_atari_env.py
  dizoo/atari/envs/test_atari_mutli_discrete_env.py
  setup.py
Labels: enhancement, env

#24 feature(pu): add WQMIX algorithm
  ding/entry/tests/test_serial_entry.py
  ding/entry/tests/test_serial_entry_algo.py
  ding/model/template/__init__.py
  ding/model/template/tests/test_wqmix.py
  ding/model/template/wqmix.py
  ding/policy/__init__.py
  ding/policy/command_mode_policy_instance.py
  ding/policy/wqmix.py
  dizoo/multiagent_particle/config/__init__.py
  dizoo/multiagent_particle/config/cooperative_navigation_wqmix_config.py
  dizoo/smac/config/smac_3s5z_wqmix_config.py
  dizoo/smac/config/smac_5m6m_wqmix_config.py
  dizoo/smac/config/smac_MMM2_wqmix_config.py
  dizoo/smac/config/smac_MMM_wqmix_config.py
Labels: serial, algo

#78 feature(nyz): add mujoco docker
  .github/workflows/deploy.yml
  Dockerfile.env
Labels: enhancement, env

#79 fix(xjx): test failed when using system proxy
  ding/interaction/base/network.py
Labels: bug

#80 feature(nyz): add smac docker
  .github/workflows/deploy.yml
  Dockerfile.env
  dizoo/smac/README.md
  dizoo/smac/envs/maps/SMAC_Maps/__init__.py
  dizoo/smac/envs/maps/SMAC_Maps_two_player/__init__.py
  dizoo/smac/envs/maps/__init__.py
  dizoo/smac/envs/smac_env.py
  dizoo/smac/envs/smac_map.py
  setup.py
Labels: enhancement, env

#76 feature(davide): Implementation of D4PG
  README.md
  ding/entry/tests/test_serial_entry.py
  ding/model/template/__init__.py
  ding/model/template/qac_dist.py
  ding/model/template/tests/test_qac_dist.py
  ding/policy/__init__.py
  ding/policy/command_mode_policy_instance.py
  ding/policy/d4pg.py
  dizoo/classic_control/cartpole/entry/cartpole_c51_main.py
  dizoo/classic_control/pendulum/config/__init__.py
  dizoo/classic_control/pendulum/config/pendulum_d4pg_config.py
  dizoo/classic_control/pendulum/entry/pendulum_d4pg_main.py
  dizoo/classic_control/pendulum/entry/pendulum_ddpg_main.py
  dizoo/d4rl/config/__init__.py
  dizoo/d4rl/envs/d4rl_env.py
  dizoo/mujoco/config/hopper_d4pg_default_config.py
  dizoo/mujoco/entry/mujoco_d4pg_main.py
  dizoo/mujoco/entry/mujoco_ddpg_main.py
Labels: serial, algo
