Repository opendilab/DI-engine, pull requests merged in 2021-11, with the labels that each got.

#122 feature(nyz): extend torch1.1.0 support
  ding/compatibility.py
  ding/model/common/encoder.py
  ding/torch_utils/checkpoint_helper.py
  ding/torch_utils/network/__init__.py
  ding/torch_utils/network/nn_module.py
  ding/torch_utils/network/resnet.py
  ding/torch_utils/network/tests/test_nn_module.py
  ding/utils/data/collate_fn.py
  dizoo/classic_control/cartpole/entry/cartpole_c51_main.py
  setup.py
Labels: enhancement

#57 feature(wyh): add guided cost algorithm
  README.md
  ding/entry/__init__.py
  ding/entry/serial_entry_guided_cost.py
  ding/policy/sac.py
  ding/reward_model/__init__.py
  ding/reward_model/guided_cost_reward_model.py
  dizoo/box2d/lunarlander/config/lunarlander_gcl_config.py
  dizoo/classic_control/cartpole/config/cartpole_gcl_config.py
  dizoo/mujoco/config/halfcheetah_gcl_config.py
  dizoo/mujoco/config/hopper_gcl_config.py
  dizoo/mujoco/config/walker2d_gcl_config.py
Labels: serial, algo

#41 feature(zt): add curiosity icm algorithm
  README.md
  ding/entry/tests/test_icm.py
  ding/policy/ppo.py
  ding/reward_model/__init__.py
  ding/reward_model/icm_reward_model.py
  dizoo/atari/config/serial/pong/pong_ppo_offpolicy_icm.py
  dizoo/classic_control/cartpole/config/cartpole_ppo_icm_config.py
  dizoo/minigrid/config/doorkey8_icm_config.py
  dizoo/minigrid/config/fourroom_icm_config.py
  dizoo/minigrid/config/minigrid_icm_config.py
  dizoo/minigrid/envs/minigrid_env.py
Labels: algo

#128 feature(nyp): add apple key to door treasure and polish
  dizoo/minigrid/__init__.py
  dizoo/minigrid/config/minigrid_ngu_config.py
  dizoo/minigrid/config/minigrid_onppo_config.py
  dizoo/minigrid/config/minigrid_r2d2_config.py
  dizoo/minigrid/config/minigrid_rnd_onppo_config.py
  dizoo/minigrid/envs/__init__.py
  dizoo/minigrid/envs/app_key_to_door_treasure.py
  dizoo/minigrid/envs/minigrid_env.py
  dizoo/minigrid/envs/test_minigrid_env.py
Labels: env

#127 fix(crb): add renew for env manager; update retry and timeout logit for subprecess env manager
  ding/envs/env_manager/base_env_manager.py
  ding/envs/env_manager/subprocess_env_manager.py
  ding/envs/env_manager/tests/conftest.py
  ding/envs/env_manager/tests/test_base_env_manager.py
  ding/envs/env_manager/tests/test_subprocess_env_manager.py
Labels: bug, serial

#126 fix(pu): add loss statistics and polish r2d3 pong config
  README.md
  ding/policy/r2d3.py
  ding/rl_utils/td.py
  dizoo/atari/config/serial/pong/pong_r2d2_config.py
  dizoo/atari/config/serial/pong/pong_r2d3_offppoexpert_config.py
  dizoo/atari/config/serial/pong/pong_r2d3_r2d2expert_config.py
  dizoo/box2d/lunarlander/config/lunarlander_r2d3_ppoexpert_config.py
  dizoo/box2d/lunarlander/config/lunarlander_r2d3_r2d2expert_config.py
Labels: algo
