Repository opendilab/DI-engine, pull requests merged in 2022-02, with the labels that each got.

#204 fix and test(zjow): turn off Parallel.is_active when stop and remake unittest file for pace controller middleware.
  ding/framework/parallel.py
  ding/framework/tests/test_middleware_pace_controller.py
Labels: parallel-dist, P3, test

#208 test(wyh):trex tests
  ding/entry/tests/test_serial_entry_trex.py
  ding/reward_model/trex_reward_model.py
  dizoo/atari/config/serial/pong/pong_ppo_offpolicy_config.py
  dizoo/atari/config/serial/pong/pong_trex_offppo_config.py
Labels: test

#210 test(wyh):test td
  ding/rl_utils/tests/test_td.py
Labels: test

#212 feature(nyz): add train_iter and env_step in serial pipeline
  ding/entry/cli.py
  ding/entry/serial_entry.py
  ding/entry/serial_entry_dqfd.py
  ding/entry/serial_entry_gail.py
  ding/entry/serial_entry_guided_cost.py
  ding/entry/serial_entry_il.py
  ding/entry/serial_entry_mbrl.py
  ding/entry/serial_entry_offline.py
  ding/entry/serial_entry_onpolicy.py
  ding/entry/serial_entry_r2d3.py
  ding/entry/serial_entry_reward_model.py
  ding/entry/serial_entry_reward_model_ngu.py
  ding/entry/serial_entry_reward_model_onpolicy.py
  ding/entry/serial_entry_sqil.py
  ding/entry/serial_entry_td3_vae.py
  ding/entry/serial_entry_trex.py
  ding/entry/serial_entry_trex_onpolicy.py
  ding/entry/tests/test_icm.py
  ding/entry/tests/test_serial_entry.py
  ding/entry/tests/test_serial_entry_dqfd.py
  ding/entry/tests/test_serial_entry_guided_cost.py
  ding/entry/tests/test_serial_entry_onpolicy.py
  ding/entry/tests/test_serial_entry_reward_model.py
  ding/entry/tests/test_serial_entry_sqil.py
  ding/entry/tests/test_serial_entry_trex.py
  ding/entry/tests/test_serial_entry_trex_onpolicy.py
  dizoo/bitflip/entry/bitflip_dqn_main.py
  dizoo/classic_control/cartpole/entry/cartpole_ppg_main.py
  dizoo/league_demo/league_demo_ppo_main.py
  dizoo/league_demo/selfplay_demo_ppo_main.py
Labels: enhancement

#214 fix(xjx): fix remote parameter in league
  ding/framework/middleware/league_dispatcher.py
Labels: bug

#211 Fix(zjow): fix pytest problem for parallel middleware.
  ding/framework/tests/test_middleware_pace_controller.py
Labels: bug

#191 fix(jrn): modify the tensor type to match the JE computation and provide an alternative optimizer
  ding/policy/dqfd.py
Labels: bug, algo

#213 feature(xjx): support async event handler and logger
  .github/workflows/unit_test.yml
  ding/framework/__init__.py
  ding/framework/event_loop.py
  ding/framework/parallel.py
  ding/framework/task.py
  ding/framework/tests/test_event_loop.py
  ding/framework/tests/test_parallel.py
  ding/framework/tests/test_task.py
  ding/framework/wrapper/step_timer.py
  ding/scripts/main_league_slurm.sh
  ding/utils/log_helper.py
  ding/utils/log_writer_helper.py
  ding/utils/tests/test_log_writer_helper.py
  pytest.ini
  setup.py
Labels: enhancement

#200 polish(whl): fix Trex bug
  ding/reward_model/trex_reward_model.py
  dizoo/atari/config/serial/spaceinvaders/spaceinvaders_trex_dqn_config.py
  dizoo/box2d/lunarlander/config/lunarlander_trex_dqn_config.py
  dizoo/mujoco/config/halfcheetah_trex_onppo_default_config.py
Labels: algo

#186 feature(szj): use log prob instead of using prob in acer
  ding/policy/acer.py
  ding/rl_utils/acer.py
Labels: algo

#220 fix(lwq): fix pdqn model template not work on gpu device
  ding/model/template/pdqn.py
Labels: bug

#221 style(nyz): add doc docker
  .github/workflows/deploy.yml
  Dockerfile.base
Labels: test

#219 feature(zjow): Change default logging handler to a rich logging handler.
  ding/entry/main_league.py
  ding/framework/event_loop.py
  ding/framework/middleware/basic_evaluator.py
  ding/framework/middleware/basic_learner.py
  ding/framework/parallel.py
  ding/framework/wrapper/step_timer.py
  ding/utils/__init__.py
  ding/utils/logging_rich_config.py
Labels: enhancement, P3

#223 feature(zjow): Minor changes to the data format and logger default level.
  ding/utils/logging_rich_config.py
Labels: enhancement, P3

#147 feature(yzj): add gym async vector env in DI-engine
  ding/envs/env_manager/__init__.py
  ding/envs/env_manager/gym_vector_env_manager.py
  ding/envs/env_manager/subprocess_env_manager.py
  ding/worker/collector/tests/speed_test/fake_env.py
  ding/worker/collector/tests/speed_test/fake_policy.py
  ding/worker/collector/tests/speed_test/test_collector_profile.py
  dizoo/atari/config/serial/pong/pong_dqfd_config.py
  dizoo/atari/config/serial/pong/pong_r2d3_offppoexpert_config.py
  dizoo/atari/config/serial/pong/pong_r2d3_r2d2expert_config.py
  dizoo/atari/config/serial/pong/pong_sqil_config.py
  dizoo/atari/config/serial/pong/pong_sql_config.py
  dizoo/atari/config/serial/pong/pong_trex_sql_config.py
  dizoo/atari/config/serial/qbert/qbert_dqfd_config.py
  dizoo/atari/config/serial/qbert/qbert_sqil_config.py
  dizoo/atari/config/serial/qbert/qbert_sql_config.py
  dizoo/atari/config/serial/spaceinvaders/spaceinvaders_dqfd_config.py
  dizoo/atari/config/serial/spaceinvaders/spaceinvaders_sqil_config.py
  dizoo/atari/config/serial/spaceinvaders/spaceinvaders_sql_config.py
  dizoo/box2d/lunarlander/config/lunarlander_dqfd_config.py
  dizoo/box2d/lunarlander/config/lunarlander_offppo_config.py
  dizoo/box2d/lunarlander/config/lunarlander_r2d3_ppoexpert_config.py
  dizoo/box2d/lunarlander/config/lunarlander_r2d3_r2d2expert_config.py
  dizoo/box2d/lunarlander/config/lunarlander_sqil_config.py
  dizoo/box2d/lunarlander/config/lunarlander_trex_dqn_config.py
  dizoo/box2d/lunarlander/config/lunarlander_trex_offppo_config.py
  dizoo/classic_control/cartpole/config/cartpole_dqfd_config.py
  dizoo/classic_control/cartpole/config/cartpole_trex_dqn_config.py
  dizoo/classic_control/cartpole/config/cartpole_trex_offppo_config.py
  dizoo/mujoco/config/ant_ppo_default_config.py
  dizoo/mujoco/config/ant_trex_onppo_default_config.py
  dizoo/mujoco/config/ant_trex_sac_default_config.py
  dizoo/mujoco/config/halfcheetah_ppo_default_config.py
  dizoo/mujoco/config/halfcheetah_trex_onppo_default_config.py
  dizoo/mujoco/config/halfcheetah_trex_sac_default_config.py
  dizoo/mujoco/config/hopper_trex_onppo_default_config.py
  dizoo/mujoco/config/hopper_trex_sac_default_config.py
  dizoo/mujoco/config/walker2d_ppo_default_config.py
  dizoo/mujoco/config/walker2d_trex_onppo_default_config.py
  dizoo/mujoco/config/walker2d_trex_sac_default_config.py
Labels: enhancement

#215 test(pu): add model wrapper unittest
  ding/model/wrapper/model_wrappers.py
  ding/model/wrapper/test_model_wrappers.py
Labels: test
