Repository opendilab/DI-engine, pull requests merged in 2022-01, with the labels that each got.

#152 feature(pu): add td3_vae algorithm
  .gitignore
  ding/entry/__init__.py
  ding/entry/serial_entry_td3_vae.py
  ding/model/template/__init__.py
  ding/model/template/tests/test_vae.py
  ding/model/template/vae.py
  ding/policy/__init__.py
  ding/policy/command_mode_policy_instance.py
  ding/policy/il.py
  ding/policy/td3_vae.py
  ding/utils/type_helper.py
  dizoo/box2d/lunarlander/config/lunarlander_cont_ddpg_config.py
  dizoo/box2d/lunarlander/config/lunarlander_cont_td3_config.py
  dizoo/box2d/lunarlander/config/lunarlander_cont_td3_vae_config.py
  dizoo/box2d/lunarlander/envs/lunarlander_env.py
Labels: algo

#185 fix(nyz): remove default n_sample/n_episode value in policy config
  ding/entry/cli.py
  ding/entry/serial_entry_offline.py
  ding/policy/acer.py
  ding/policy/collaq.py
  ding/policy/coma.py
  ding/policy/cql.py
  ding/policy/d4pg.py
  ding/policy/ddpg.py
  ding/policy/impala.py
  ding/policy/ngu.py
  ding/policy/qmix.py
  ding/policy/r2d2.py
  ding/policy/r2d2_collect_traj.py
  ding/policy/r2d3.py
  ding/policy/sac.py
  ding/policy/sql.py
  ding/policy/td3.py
  ding/policy/td3_vae.py
  ding/policy/wqmix.py
  dizoo/classic_control/cartpole/config/cartpole_cql_config.py
  dizoo/classic_control/pendulum/config/pendulum_cql_config.py
  dizoo/classic_control/pendulum/config/pendulum_td3_bc_config.py
  dizoo/d4rl/config/halfcheetah_td3bc_medium_expert_config.py
  dizoo/d4rl/config/hopper_cql_default_config.py
  dizoo/d4rl/config/hopper_expert_cql_default_config.py
  dizoo/d4rl/config/hopper_medium_cql_default_config.py
  dizoo/d4rl/config/hopper_td3bc_medium_expert_config.py
  dizoo/d4rl/config/walker2d_td3bc_medium_expert_config.py
  dizoo/mujoco/config/hopper_cql_default_config.py
  dizoo/mujoco/config/hopper_td3_bc_default_config.py
Labels: serial, algo

#189 polish(nyp): polish a2c qbert config
  dizoo/atari/config/serial/qbert/qbert_a2c_config.py
Labels: env, algo

#190 fixbug(zlx): random_collect compatible to episode collector
  .flake8
  ding/entry/__init__.py
  ding/entry/serial_entry.py
  ding/entry/serial_entry_dqfd.py
  ding/entry/serial_entry_gail.py
  ding/entry/serial_entry_guided_cost.py
  ding/entry/serial_entry_mbrl.py
  ding/entry/serial_entry_r2d3.py
  ding/entry/serial_entry_reward_model.py
  ding/entry/serial_entry_reward_model_ngu.py
  ding/entry/serial_entry_reward_model_onpolicy.py
  ding/entry/serial_entry_sqil.py
  ding/entry/serial_entry_td3_vae.py
  ding/entry/serial_entry_trex.py
  ding/entry/tests/test_random_collect.py
  ding/entry/utils.py
  dizoo/minigrid/config/minigrid_ngu_config.py
Labels: bug, refactor

#192 benchmark(zlx): bitflip-herdqn benchmark
  dizoo/classic_control/bitflip/config/bitflip_her_dqn_config.py
  dizoo/classic_control/bitflip/entry/bitflip_dqn_main.py
Labels: algo

#197 polish(zlx): move bitflip out of classic_control
  README.md
  ding/entry/tests/test_serial_entry.py
  ding/entry/tests/test_serial_entry_algo.py
  dizoo/bitflip/README.md
  dizoo/bitflip/__init__.py
  dizoo/bitflip/bitflip.gif
  dizoo/bitflip/config/__init__.py
  dizoo/bitflip/config/bitflip_her_dqn_config.py
  dizoo/bitflip/config/bitflip_pure_dqn_config.py
  dizoo/bitflip/entry/__init__.py
  dizoo/bitflip/entry/bitflip_dqn_main.py
  dizoo/bitflip/envs/__init__.py
  dizoo/bitflip/envs/bitflip_env.py
  dizoo/bitflip/envs/test_bitfile_env.py
Labels: env

#198 feature(zjow): Add pace controller middleware for new task framework
  ding/framework/middleware/__init__.py
  ding/framework/middleware/pace_controller.py
  ding/framework/tests/test_middleware_pace_controller.py
Labels: enhancement
