Repository opendilab/DI-engine, pull requests merged in 2022-05, with the labels that each got.

#298 benchmark(davide): gail-mujoco
  dizoo/box2d/bipedalwalker/config/bipedalwalker_gail_sac_config.py
  dizoo/box2d/lunarlander/config/lunarlander_gail_dqn_config.py
  dizoo/mujoco/config/ant_gail_sac_config.py
  dizoo/mujoco/config/halfcheetah_gail_sac_config.py
  dizoo/mujoco/config/walker2d_gail_sac_config.py
Labels: config

#307 feature(xjx): ensure item length in each group is greater than unroll_len
  ding/data/buffer/deque_buffer.py
  ding/data/buffer/tests/test_buffer.py
Labels: enhancement

#317 polish(lxl&zms): add middleware comments
  ding/framework/middleware/ckpt_handler.py
  ding/framework/middleware/collector.py
  ding/framework/middleware/functional/advantage_estimator.py
  ding/framework/middleware/functional/collector.py
  ding/framework/middleware/functional/data_processor.py
  ding/framework/middleware/functional/enhancer.py
  ding/framework/middleware/functional/evaluator.py
  ding/framework/middleware/functional/explorer.py
  ding/framework/middleware/functional/trainer.py
  ding/framework/middleware/learner.py
Labels: doc

#315 polish(davide): polish files in ding/model/common
  ding/model/common/encoder.py
  ding/model/common/head.py
  ding/model/common/utils.py
Labels: doc

#320 feature(zzh): log videos to tensorboard
  ding/envs/env_manager/base_env_manager.py
  ding/envs/env_manager/subprocess_env_manager.py
  ding/utils/__init__.py
  ding/utils/render_helper.py
  ding/worker/collector/base_serial_evaluator.py
  ding/worker/collector/interaction_serial_evaluator.py
  dizoo/atari/config/serial/pong/pong_dqn_render_config.py
  setup.py
Labels: enhancement

#326 feature(lxl): add infoNCE loss
  .coveragerc
  README.md
  ding/entry/tests/test_serial_entry.py
  ding/policy/__init__.py
  ding/policy/command_mode_policy_instance.py
  ding/policy/dqn.py
  ding/torch_utils/__init__.py
  ding/torch_utils/loss/__init__.py
  ding/torch_utils/loss/contrastive_loss.py
  ding/torch_utils/loss/tests/test_contrastive_loss.py
  dizoo/atari/config/serial/pong/pong_dqn_stdim_config.py
  dizoo/classic_control/cartpole/config/cartpole_dqn_stdim_config.py
Labels: algo

#343 fix(pu): fix ngu model and minigrid env
  ding/model/template/ngu.py
  ding/model/template/q_learning.py
  ding/policy/r2d2.py
  ding/policy/r2d2_collect_traj.py
  ding/policy/r2d3.py
  ding/policy/tests/test_r2d3.py
  dizoo/atari/config/serial/pong/pong_r2d3_offppoexpert_config.py
  dizoo/atari/config/serial/pong/pong_r2d3_r2d2expert_config.py
  dizoo/box2d/lunarlander/config/lunarlander_r2d3_ppoexpert_config.py
  dizoo/box2d/lunarlander/config/lunarlander_r2d3_r2d2expert_config.py
  dizoo/minigrid/envs/minigrid_env.py
Labels: bug

#344 feature(zjow): add dmc2gym env
  .github/workflows/deploy.yml
  dizoo/dmc2gym/__init__.py
  dizoo/dmc2gym/envs/__init__.py
  dizoo/dmc2gym/envs/dmc2gym_env.py
  dizoo/dmc2gym/envs/test_dmc2gym_env.py
  docker/Dockerfile.env
  setup.py
Labels: env
