Repository opendilab/DI-engine, pull requests merged in 2022-11, with the labels that each got.

#534 feature(zjow): add trackback log for subprocess env manager
  ding/envs/env_manager/subprocess_env_manager.py
Labels: enhancement

#526 env(zjow): add env gym_pybullet_drones
  README.md
  ding/entry/serial_entry_onpolicy.py
  dizoo/gym_pybullet_drones/__init__.py
  dizoo/gym_pybullet_drones/config/flythrugate_onppo_config.py
  dizoo/gym_pybullet_drones/config/takeoffaviary_onppo_config.py
  dizoo/gym_pybullet_drones/entry/flythrugate_onppo_eval.py
  dizoo/gym_pybullet_drones/entry/takeoffaviary_onppo_eval.py
  dizoo/gym_pybullet_drones/envs/__init__.py
  dizoo/gym_pybullet_drones/envs/gym_pybullet_drones_env.py
  dizoo/gym_pybullet_drones/envs/test_ding_env.py
  dizoo/gym_pybullet_drones/envs/test_ori_env.py
  dizoo/gym_pybullet_drones/gym_pybullet_drones.gif
Labels: env

#537 fix(zjow): fix halfcheetah td3 config file.
  dizoo/mujoco/config/halfcheetah_td3_config.py
Labels: bug, config

#512 env(lisong): add beergame supply chain optimization env
  README.md
  ding/envs/env_manager/base_env_manager.py
  ding/worker/collector/episode_serial_collector.py
  ding/worker/collector/interaction_serial_evaluator.py
  dizoo/beergame/beergame.png
  dizoo/beergame/config/beergame_onppo_config.py
  dizoo/beergame/entry/beergame_eval.py
  dizoo/beergame/envs/BGAgent.py
  dizoo/beergame/envs/__init__.py
  dizoo/beergame/envs/beergame_core.py
  dizoo/beergame/envs/beergame_env.py
  dizoo/beergame/envs/clBeergame.py
  dizoo/beergame/envs/plotting.py
  dizoo/beergame/envs/utils.py
Labels: env

#541 fix(wzl): fix bugs for dict obs in new pipeline
  ding/envs/env_manager/subprocess_env_manager.py
  ding/framework/middleware/functional/collector.py
  ding/framework/middleware/functional/evaluator.py
  ding/torch_utils/__init__.py
  ding/torch_utils/data_helper.py
Labels: bug

#538 feature(nyz): add evaluator more info viz support
  ding/envs/env_manager/subprocess_env_manager.py
  ding/framework/middleware/functional/collector.py
  ding/framework/middleware/functional/evaluator.py
  ding/torch_utils/__init__.py
  ding/torch_utils/data_helper.py
Labels: enhancement

#525 feature(whl): add more DingEnvWrapper example
  dizoo/dmc2gym/config/dmc2gym_ppo_config.py
  dizoo/dmc2gym/entry/dmc2gym_onppo_main.py
  dizoo/minigrid/entry/minigrid_onppo_main.py
  dizoo/procgen/config/__init__.py
  dizoo/procgen/config/bigfish_plr_config.py
  dizoo/procgen/config/bigfish_ppg_config.py
  dizoo/procgen/config/coinrun_dqn_config.py
  dizoo/procgen/config/coinrun_ppg_config.py
  dizoo/procgen/config/coinrun_ppo_config.py
  dizoo/procgen/config/maze_dqn_config.py
  dizoo/procgen/config/maze_ppg_config.py
  dizoo/procgen/config/maze_ppo_config.py
  dizoo/procgen/entry/coinrun_onppo_main.py
  dizoo/rocket/entry/rocket_hover_onppo_main_v2.py
  dizoo/rocket/entry/rocket_landing_onppo_main_v2.py
Labels: env

#540 feature(wyh): madqn algorithm
  ding/entry/tests/test_serial_entry.py
  ding/model/template/__init__.py
  ding/model/template/madqn.py
  ding/model/template/tests/test_madqn.py
  ding/policy/command_mode_policy_instance.py
  ding/policy/madqn.py
  dizoo/petting_zoo/config/__init__.py
  dizoo/petting_zoo/config/ptz_simple_spread_madqn_config.py
  dizoo/smac/config/smac_3s5z_madqn_config.py
  dizoo/smac/config/smac_3s5zvs3s6z_madqn_config.py
  dizoo/smac/config/smac_5m6m_madqn_config.py
  dizoo/smac/config/smac_8m9m_madqn_config.py
  dizoo/smac/config/smac_MMM2_madqn_config.py
  dizoo/smac/config/smac_MMM_madqn_config.py
Labels: algo

#542 feature(zjow): add load and save method for replaybuffer
  ding/data/buffer/buffer.py
  ding/data/buffer/deque_buffer.py
  ding/data/buffer/deque_buffer_wrapper.py
  ding/data/buffer/tests/test_buffer.py
  ding/framework/middleware/functional/__init__.py
  ding/framework/middleware/functional/data_processor.py
  ding/framework/middleware/tests/test_advantage_estimator.py
  ding/framework/middleware/tests/test_data_processor.py
  ding/worker/replay_buffer/advanced_buffer.py
  ding/worker/replay_buffer/base_buffer.py
  ding/worker/replay_buffer/naive_buffer.py
  ding/worker/replay_buffer/tests/test_advanced_buffer.py
  ding/worker/replay_buffer/tests/test_naive_buffer.py
  setup.py
Labels: enhancement
