Repository opendilab/DI-engine, pull requests merged in 2022-09, with the labels that each got.

#464 config(wyh):add mappo multi-mujoco
  ding/model/template/mavac.py
  dizoo/multiagent_mujoco/config/ant_mappo_config.py
Labels: config

#449 feature(rjy): add rocket env
  ding/framework/middleware/functional/advantage_estimator.py
  dizoo/rocket/config/rocket_hover_ppo_config.py
  dizoo/rocket/config/rocket_landing_ppo_config.py
  dizoo/rocket/entry/rocket_hover_ppo_main.py
  dizoo/rocket/entry/rocket_landing_ppo_main.py
  dizoo/rocket/envs/rocket_env.py
  dizoo/rocket/envs/test_rocket_env.py
  setup.py
Labels: env

#452 feature(i-am-tc) : Mountain Car (discrete action) environment
  dizoo/classic_control/mountain_car/__init__.py
  dizoo/classic_control/mountain_car/config/mtcar_rainbow_config.py
  dizoo/classic_control/mountain_car/envs/__init__.py
  dizoo/classic_control/mountain_car/envs/mtcar_env.py
  dizoo/classic_control/mountain_car/envs/test_mtcar_env.py
Labels: env

#401 feature(zzh): add IBC algorithm
  README.md
  ding/entry/serial_entry_offline.py
  ding/entry/tests/test_serial_entry.py
  ding/envs/env_wrappers/env_wrappers.py
  ding/model/template/ebm.py
  ding/model/template/tests/test_ebm.py
  ding/policy/__init__.py
  ding/policy/command_mode_policy_instance.py
  ding/policy/ibc.py
  ding/policy/mbpolicy/mbsac.py
  ding/policy/td3_bc.py
  ding/utils/__init__.py
  ding/utils/data/dataset.py
  ding/utils/data/tests/test_dataset.py
  ding/utils/registry_factory.py
  ding/worker/collector/interaction_serial_evaluator.py
  dizoo/classic_control/pendulum/config/pendulum_ibc_config.py
  dizoo/classic_control/pendulum/config/pendulum_td3_bc_config.py
  dizoo/d4rl/config/halfcheetah_expert_td3bc_config.py
  dizoo/d4rl/config/halfcheetah_medium_expert_td3bc_config.py
  dizoo/d4rl/config/halfcheetah_medium_replay_td3bc_config.py
  dizoo/d4rl/config/halfcheetah_medium_td3bc_config.py
  dizoo/d4rl/config/halfcheetah_random_td3bc_config.py
  dizoo/d4rl/config/hopper_expert_td3bc_config.py
  dizoo/d4rl/config/hopper_medium_expert_bc_config.py
  dizoo/d4rl/config/hopper_medium_expert_ibc_ar_config.py
  dizoo/d4rl/config/hopper_medium_expert_ibc_config.py
  dizoo/d4rl/config/hopper_medium_expert_ibc_mcmc_config.py
  dizoo/d4rl/config/hopper_medium_expert_td3bc_config.py
  dizoo/d4rl/config/hopper_medium_replay_td3bc_config.py
  dizoo/d4rl/config/hopper_medium_td3bc_config.py
  dizoo/d4rl/config/hopper_random_td3bc_config.py
  dizoo/d4rl/config/kitchen_complete_bc_config.py
  dizoo/d4rl/config/kitchen_complete_ibc_ar_config.py
  dizoo/d4rl/config/kitchen_complete_ibc_config.py
  dizoo/d4rl/config/kitchen_complete_ibc_mcmc_config.py
  dizoo/d4rl/config/pen_human_bc_config.py
  dizoo/d4rl/config/pen_human_ibc_ar_config.py
  dizoo/d4rl/config/pen_human_ibc_config.py
  dizoo/d4rl/config/pen_human_ibc_mcmc_config.py
  dizoo/d4rl/config/walker2d_expert_td3bc_config.py
  dizoo/d4rl/config/walker2d_medium_expert_td3bc_config.py
  dizoo/d4rl/config/walker2d_medium_replay_td3bc_config.py
  dizoo/d4rl/config/walker2d_medium_td3bc_config.py
  dizoo/d4rl/config/walker2d_random_td3bc_config.py
  dizoo/d4rl/entry/d4rl_cql_main.py
  dizoo/d4rl/entry/d4rl_ibc_main.py
  dizoo/d4rl/entry/d4rl_td3_bc_main.py
  dizoo/d4rl/envs/d4rl_env.py
  dizoo/d4rl/envs/d4rl_wrappers.py
  dizoo/mujoco/config/hopper_td3_bc_config.py
  setup.py
Labels: algo

#467 feature(zms): update ctx to dataclass
  ding/framework/context.py
  ding/framework/middleware/functional/ctx_helper.py
  ding/framework/middleware/functional/evaluator.py
  ding/framework/middleware/functional/trainer.py
  ding/framework/tests/context_fake_data.py
  ding/framework/tests/test_context.py
Labels: enhancement

#427 polish(rjy): polish notes for q-learning
  ding/model/common/head.py
  ding/model/template/q_learning.py
Labels: doc

#474 revise(zjow): revision to mujoco dockerfile and validation
  docker/Dockerfile.env
Labels: docker

#414 feature(crb): add continuous space for PPOPG policy
  ding/policy/ppo.py
  ding/rl_utils/__init__.py
  ding/rl_utils/ppo.py
  dizoo/box2d/bipedalwalker/config/bipedalwalker_ppopg_config.py
Labels: algo

#342 fix(mahuangxu): data collection errors caused by shallow copies
  ding/worker/collector/base_serial_collector.py
  ding/worker/collector/sample_serial_collector.py
Labels: enhancement

#425 feature(xjx): new style dist version, add storage loader and model loader
  ding/data/__init__.py
  ding/data/buffer/tests/test_buffer_benchmark.py
  ding/data/model_loader.py
  ding/data/shm_buffer.py
  ding/data/storage/__init__.py
  ding/data/storage/file.py
  ding/data/storage/storage.py
  ding/data/storage/tests/test_storage.py
  ding/data/storage_loader.py
  ding/data/tests/test_model_loader.py
  ding/data/tests/test_shm_buffer.py
  ding/data/tests/test_storage_loader.py
  ding/entry/cli_ditask.py
  ding/entry/cli_parsers/k8s_parser.py
  ding/entry/cli_parsers/slurm_parser.py
  ding/entry/cli_parsers/tests/test_slurm_parser.py
  ding/entry/tests/test_cli_ditask.py
  ding/envs/env_manager/env_supervisor.py
  ding/envs/env_manager/subprocess_env_manager.py
  ding/example/__init__.py
  ding/example/dqn.py
  ding/example/dqn_dist.py
  ding/framework/__init__.py
  ding/framework/event_loop.py
  ding/framework/middleware/__init__.py
  ding/framework/middleware/ckpt_handler.py
  ding/framework/middleware/collector.py
  ding/framework/middleware/distributer.py
  ding/framework/middleware/functional/__init__.py
  ding/framework/middleware/functional/advantage_estimator.py
  ding/framework/middleware/functional/data_processor.py
  ding/framework/middleware/functional/enhancer.py
  ding/framework/middleware/functional/evaluator.py
  ding/framework/middleware/functional/exchanger.py
  ding/framework/middleware/functional/explorer.py
  ding/framework/middleware/functional/timer.py
  ding/framework/middleware/learner.py
  ding/framework/middleware/tests/test_ckpt_handler.py
  ding/framework/middleware/tests/test_distributer.py
  ding/framework/middleware/tests/test_enhancer.py
  ding/framework/parallel.py
  ding/framework/supervisor.py
  ding/framework/task.py
  ding/framework/tests/test_event_loop.py
  ding/framework/tests/test_parallel.py
  ding/framework/tests/test_supervisor.py
  ding/framework/tests/test_task.py
  ding/framework/wrapper/step_timer.py
Labels: efficiency optimization, refactor

#479 fix(nyz): fix di-orchestrator version bug in unittest
  ding/utils/tests/test_k8s_launcher.py
Labels: bug

#481 fix(nyz): fix a2c policy batch size bug
  ding/policy/a2c.py
  dizoo/box2d/lunarlander/config/lunarlander_a2c_config.py
  dizoo/classic_control/cartpole/config/cartpole_a2c_config.py
Labels: algo, config

#483 fix(cpwan): fix the type conversion in ding_env_wrapper
  ding/envs/env/ding_env_wrapper.py
Labels: enhancement

#465 feature(rjy): add rule-based gomoku expert action
  dizoo/board_games/gomoku/envs/gomoku_env.py
  dizoo/board_games/gomoku/envs/gomoku_expert.py
  dizoo/board_games/gomoku/envs/test_gomoku_expert_action.py
Labels: enhancement

#486 feature(nyz): IGM ding support
  ding/config/config.py
  ding/config/tests/test_config_formatted.py
  ding/utils/k8s_helper.py
  ding/utils/plot_helper.py
  ding/utils/tests/test_plot.py
  dizoo/classic_control/cartpole/config/cartpole_ppo_config.py
  dizoo/classic_control/cartpole/config/cartpole_r2d2_config.py
  dizoo/classic_control/cartpole/config/cartpole_rainbow_config.py
  dizoo/gym_anytrading/envs/trading_env.py
  setup.py
Labels: enhancement

#453 polish(rjy): adjust location of the default_model method in policy class
  ding/policy/a2c.py
  ding/policy/acer.py
  ding/policy/atoc.py
  ding/policy/bc.py
  ding/policy/c51.py
  ding/policy/collaq.py
  ding/policy/coma.py
  ding/policy/cql.py
  ding/policy/d4pg.py
  ding/policy/ddpg.py
  ding/policy/decision_transformer.py
  ding/policy/dqn.py
  ding/policy/fqf.py
  ding/policy/il.py
  ding/policy/impala.py
  ding/policy/iqn.py
  ding/policy/ngu.py
  ding/policy/offppo_collect_traj.py
  ding/policy/pdqn.py
  ding/policy/ppg.py
  ding/policy/qmix.py
  ding/policy/qrdqn.py
  ding/policy/qtran.py
  ding/policy/r2d2.py
  ding/policy/r2d2_collect_traj.py
  ding/policy/r2d2_gtrxl.py
  ding/policy/r2d3.py
  ding/policy/rainbow.py
  ding/policy/sac.py
  ding/policy/sql.py
  ding/policy/sqn.py
  ding/policy/td3_vae.py
  ding/policy/wqmix.py
Labels: doc

#490 style(hus): add readme tutorial link(environment & algorithm)
  README.md
Labels: doc

#493 style(hus): update environment & algorithm tutorial link
  README.md
Labels: doc

#489 feature(wyh): pcgrad optimizer
  README.md
  ding/torch_utils/optimizer_helper.py
  ding/torch_utils/tests/test_optimizer.py
Labels: algo
