Repository opendilab/DI-engine, pull requests merged in 2022-10, with the labels that each got.

#500 polish(pu): adapt minigrid_env and related config to latest MiniGrid v2.0.0
  dizoo/minigrid/config/minigrid_icm_offppo_config.py
  dizoo/minigrid/config/minigrid_ngu_config.py
  dizoo/minigrid/config/minigrid_offppo_config.py
  dizoo/minigrid/config/minigrid_onppo_config.py
  dizoo/minigrid/config/minigrid_onppo_stdim_config.py
  dizoo/minigrid/config/minigrid_r2d2_config.py
  dizoo/minigrid/config/minigrid_rnd_onppo_config.py
  dizoo/minigrid/envs/app_key_to_door_treasure.py
  dizoo/minigrid/envs/minigrid_env.py
  setup.py
Labels: env

#503 style(hus): update email address
  README.md
Labels: doc

#499 feature(zms): add new properties in Context
  ding/framework/context.py
  ding/framework/middleware/functional/collector.py
  ding/framework/tests/context_fake_data.py
Labels: enhancement

#504 fix(pu): fix total_loss calculation in pdqn.py
  ding/policy/pdqn.py
Labels: bug

#495 env(davide): add evogym support
  .gitignore
  README.md
  dizoo/evogym/__init__.py
  dizoo/evogym/config/bridgewalker_ddpg_config.py
  dizoo/evogym/config/walker_ddpg_config.py
  dizoo/evogym/config/walker_ddpg_eval_config.py
  dizoo/evogym/envs/__init__.py
  dizoo/evogym/envs/evogym_env.py
  dizoo/evogym/envs/test/test_evogym_env.py
  dizoo/evogym/envs/test/visualize_simple_env.py
  dizoo/evogym/envs/viewer.py
  dizoo/evogym/envs/world_data/carry_bot.json
  dizoo/evogym/envs/world_data/simple_evironment.json
  dizoo/evogym/envs/world_data/speed_bot.json
  dizoo/evogym/evogym.gif
Labels: env

#488 feature(lxy): add wandb middleware
  ding/framework/context.py
  ding/framework/middleware/functional/__init__.py
  ding/framework/middleware/functional/evaluator.py
  ding/framework/middleware/functional/logger.py
  ding/framework/middleware/tests/test_logger.py
  ding/policy/dqn.py
  setup.py
Labels: enhancement

#511 feature(pu): add some features in MLP and ResBlock
  ding/rl_utils/efficientzero/game.py
  ding/rl_utils/efficientzero/utils.py
  ding/rl_utils/tests/test_muzero_utils.py
  ding/torch_utils/network/nn_module.py
  ding/torch_utils/network/res_block.py
  ding/torch_utils/network/tests/test_nn_module.py
  ding/torch_utils/network/tests/test_res_block.py
Labels: enhancement

#523 feature(lxy): add offline wandb
  ding/framework/middleware/functional/__init__.py
  ding/framework/middleware/functional/logger.py
  ding/framework/middleware/tests/test_logger.py
  setup.py
Labels: enhancement

#528 polish(lxy): add wandb anonymous mode parameter
  ding/framework/middleware/functional/logger.py
  ding/framework/middleware/tests/test_logger.py
Labels: enhancement

#527 env(zjow): fix evogym replay video problem
  dizoo/evogym/config/bridgewalker_ddpg_config.py
  dizoo/evogym/config/carrier_ppo_config.py
  dizoo/evogym/config/walker_ddpg_config.py
  dizoo/evogym/config/walker_ddpg_eval_config.py
  dizoo/evogym/config/walker_ppo_config.py
  dizoo/evogym/entry/walker_ppo_eval.py
  dizoo/evogym/envs/evogym_env.py
  dizoo/evogym/envs/viewer.py
Labels: env
