Repository opendilab/DI-engine, pull requests merged in 2022-06, with the labels that each got.

#332 feature&optim(zzh): add DDPPO & add model-based SAC with lambda-return target & refactor MBRL pipeline
  README.md
  ding/config/config.py
  ding/entry/__init__.py
  ding/entry/serial_entry_mbrl.py
  ding/entry/tests/test_serial_entry_mbrl.py
  ding/model/template/__init__.py
  ding/model/template/model_based/__init__.py
  ding/model/template/model_based/mbpo.py
  ding/model/template/tests/test_mbpo.py
  ding/policy/command_mode_policy_instance.py
  ding/policy/mbpolicy/__init__.py
  ding/policy/mbpolicy/mbsac.py
  ding/policy/mbpolicy/tests/test_mbpolicy_utils.py
  ding/policy/mbpolicy/tests/test_mbsac.py
  ding/policy/mbpolicy/utils.py
  ding/rl_utils/td.py
  ding/utils/__init__.py
  ding/utils/registry_factory.py
  ding/worker/learner/base_learner.py
  ding/world_model/__init__.py
  ding/world_model/base_world_model.py
  ding/world_model/ddppo.py
  ding/world_model/mbpo.py
  ding/world_model/model/ensemble.py
  ding/world_model/model/tests/test_ensemble.py
  ding/world_model/tests/test_ddppo.py
  ding/world_model/tests/test_mbpo.py
  ding/world_model/tests/test_world_model.py
  ding/world_model/tests/test_world_model_utils.py
  ding/world_model/utils.py
  dizoo/classic_control/pendulum/config/mbrl/pendulum_mbsac_ddppo_config.py
  dizoo/classic_control/pendulum/config/mbrl/pendulum_mbsac_mbpo_config.py
  dizoo/classic_control/pendulum/config/mbrl/pendulum_sac_ddppo_config.py
  dizoo/classic_control/pendulum/config/mbrl/pendulum_sac_mbpo_config.py
  dizoo/classic_control/pendulum/envs/pendulum_env.py
  dizoo/mujoco/config/ant_sac_mbpo_default_config.py
  dizoo/mujoco/config/humanoid_sac_mbpo_default_config.py
  dizoo/mujoco/config/mbrl/halfcheetah_mbsac_mbpo_config.py
  dizoo/mujoco/config/mbrl/halfcheetah_sac_mbpo_config.py
  dizoo/mujoco/config/mbrl/hopper_mbsac_mbpo_config.py
  dizoo/mujoco/config/mbrl/hopper_sac_mbpo_config.py
  dizoo/mujoco/config/mbrl/walker2d_mbsac_mbpo_config.py
  dizoo/mujoco/config/mbrl/walker2d_sac_mbpo_config.py
  dizoo/mujoco/envs/__init__.py
  dizoo/mujoco/envs/mujoco_env.py
  dizoo/mujoco/envs/mujoco_gym_env.py
  dizoo/mujoco/envs/mujoco_model_env.py
Labels: algo, refactor

#347 doc(lxl): update quickstart colab link
  README.md
Labels: doc

#330 feature(xjx): add env supervisor
  Makefile
  ding/data/buffer/buffer.py
  ding/entry/tests/test_serial_entry.py
  ding/entry/tests/test_serial_entry_onpolicy.py
  ding/envs/common/common_function.py
  ding/envs/env/env_implementation_check.py
  ding/envs/env_manager/__init__.py
  ding/envs/env_manager/env_supervisor.py
  ding/envs/env_manager/tests/conftest.py
  ding/envs/env_manager/tests/test_env_supervisor.py
  ding/example/dqn_new_env.py
  ding/framework/__init__.py
  ding/framework/middleware/collector.py
  ding/framework/middleware/functional/collector.py
  ding/framework/supervisor.py
  ding/framework/tests/test_supervisor.py
  ding/utils/log_writer_helper.py
  ding/worker/collector/tests/speed_test/test_collector_profile.py
  dizoo/classic_control/cartpole/config/cartpole_dqn_config.py
Labels: enhancement, parallel-dist

#318 feature(whl): add continuous bc
  ding/entry/application_entry_drex_collect_data.py
  ding/entry/serial_entry_bc.py
  ding/entry/tests/test_serial_entry_bc.py
  ding/model/template/__init__.py
  ding/model/template/bc.py
  ding/model/template/tests/test_bc.py
  ding/policy/__init__.py
  ding/policy/bc.py
  dizoo/mujoco/example/mujoco_bc_main.py
Labels: algo

#348 polish(lisong): add sqil cosine similarity of expert and agent gradient
  ding/entry/serial_entry_sqil.py
  ding/policy/__init__.py
  ding/policy/command_mode_policy_instance.py
  ding/policy/sac.py
  dizoo/mujoco/config/halfcheetah_sqil_sac_config.py
  dizoo/mujoco/config/hopper_sqil_sac_config.py
  dizoo/mujoco/config/walker2d_sqil_sac_config.py
Labels: algo

#327 feature(wzl): decision transformer code adaptation on BipedalWalker and Hopper
  .gitignore
  ding/entry/serial_entry_decision_transformer.py
  ding/model/template/__init__.py
  ding/model/template/decision_transformer.py
  ding/model/template/tests/test_decision_transformer.py
  ding/policy/command_mode_policy_instance.py
  ding/policy/decision_transformer.py
  ding/rl_utils/__init__.py
  ding/rl_utils/td.py
  ding/utils/data/dataset.py
  dizoo/box2d/bipedalwalker/config/bipedalwalker_dt_config.py
  dizoo/box2d/bipedalwalker/dt_data/bipedalwalker_collect_data.py
  dizoo/box2d/bipedalwalker/dt_data/bipedalwalker_sac_data_config.py
  dizoo/box2d/bipedalwalker/dt_data/collect_sac_data_config.py
  dizoo/box2d/lunarlander/config/lunarlander_decision_transformer.py
  dizoo/box2d/lunarlander/config/lunarlander_dqn_config.py
  dizoo/box2d/lunarlander/dt_data/collect_dqn_data_config.py
  dizoo/box2d/lunarlander/dt_data/lunarlander_collect_data.py
  dizoo/box2d/lunarlander/dt_data/lunarlander_show_data.py
  dizoo/classic_control/cartpole/config/cartpole_decision_transformer.py
  dizoo/classic_control/cartpole/dt_data/cartpole_collect_data.py
  dizoo/classic_control/cartpole/dt_data/cartpole_show_data.py
  dizoo/classic_control/cartpole/dt_data/collect_qrdqn_data_config.py
  dizoo/d4rl/config/halfcheetah_expert_dt_config.py
  dizoo/d4rl/config/halfcheetah_medium_dt_config.py
  dizoo/d4rl/config/halfcheetah_medium_expert_dt_config.py
  dizoo/d4rl/config/halfcheetah_medium_replay_dt_config.py
  dizoo/d4rl/config/halfcheetah_random_dt_config.py
  dizoo/d4rl/config/hopper_expert_dt_config.py
  dizoo/d4rl/config/hopper_medium_dt_config.py
  dizoo/d4rl/config/hopper_medium_expert_dt_config.py
  dizoo/d4rl/config/hopper_medium_replay_dt_config.py
  dizoo/d4rl/config/hopper_random_dt_config.py
  dizoo/d4rl/config/walker2d_expert_dt_config.py
  dizoo/d4rl/config/walker2d_medium_dt_config.py
  dizoo/d4rl/config/walker2d_medium_expert_dt_config.py
  dizoo/d4rl/config/walker2d_medium_replay_dt_config.py
  dizoo/d4rl/config/walker2d_random_dt_config.py
  dizoo/d4rl/dt_data/data/plot_figure_data.py
  dizoo/d4rl/dt_data/download_data.py
  dizoo/d4rl/entry/d4rl_dt_main.py
  dizoo/petting_zoo/config/ptz_simple_spread_masac_config.py
  dizoo/petting_zoo/config/ptz_simple_spread_qmix_config.py
Labels: algo

#360 feature(zjow): Add dmc2gym replay video recording settings.
  dizoo/dmc2gym/entry/dmc2gym_save_replay_example.py
  dizoo/dmc2gym/envs/dmc2gym_env.py
Labels: env

#362 fix(lxy): fix import path error in lunarlander
  dizoo/box2d/lunarlander/config/__init__.py
Labels: bug

#378 polish(zjow): impala cnn encoder refactor.
  ding/model/common/__init__.py
  ding/model/common/encoder.py
  ding/model/common/tests/test_encoder.py
  ding/model/template/tests/test_vac.py
  ding/model/template/vac.py
  ding/torch_utils/network/__init__.py
  ding/torch_utils/network/nn_module.py
  ding/torch_utils/network/tests/test_nn_module.py
Labels: refactor

#385 fix(zjow): fix for dmc env replay and opengl settings
  dizoo/dmc2gym/envs/test_dmc2gym_env.py
  docker/Dockerfile.env
Labels: bug

#370 test(wyh):add plot test code
  ding/utils/tests/test_plot.py
  setup.py
Labels: test

#382 feature(nyz): add pure ppo policy gradient policy
  ding/entry/tests/test_serial_entry_onpolicy.py
  ding/model/template/bc.py
  ding/policy/__init__.py
  ding/policy/command_mode_policy_instance.py
  ding/policy/ppo.py
  dizoo/classic_control/cartpole/config/cartpole_ppopg_config.py
Labels: algo

#386 style(nyz): update mujoco docker download path
  docker/Dockerfile.base
  docker/Dockerfile.env
Labels: env

#371 doc(lxl): add buffer api description
  ding/data/buffer/deque_buffer.py
  ding/data/buffer/middleware/clone_object.py
  ding/data/buffer/middleware/priority.py
  ding/data/buffer/middleware/sample_range_view.py
  ding/data/buffer/middleware/staleness_check.py
  ding/data/buffer/middleware/use_time_check.py
Labels: doc

#391 fix(zjow): fix bugs in dmc2gym env.
  ding/envs/env_manager/base_env_manager.py
  ding/utils/render_helper.py
  dizoo/dmc2gym/envs/dmc2gym_env.py
  docker/Dockerfile.env
Labels: bug

#400 fix(xjx): remove pace controller
  ding/framework/middleware/functional/__init__.py
  ding/framework/middleware/functional/pace_controller.py
  ding/framework/middleware/tests/test_pace_controller.py
Labels: bug

#380 feature(whl):add trex example
  ding/example/trex.py
  dizoo/classic_control/cartpole/config/cartpole_trex_dqn_config.py
Labels: enhancement

#395 test(rjy): add discrete pendulum env
  dizoo/classic_control/pendulum/config/pedulum_dqn_config.py
  dizoo/classic_control/pendulum/envs/pendulum_env.py
  dizoo/classic_control/pendulum/envs/test_pendulum_env.py
Labels: env

#384 dev(lwq): add continuous examples: ddpg, td3 and d4pg
  ding/example/d4pg.py
  ding/example/ddpg.py
  ding/example/td3.py
  dizoo/classic_control/pendulum/config/pendulum_d4pg_config.py
Labels: enhancement

#404 polish(lwq): polish VAE
  ding/model/template/vae.py
Labels: doc
