Repository opendilab/DI-engine, pull requests merged in 2023-05, with the labels that each got.

#660 polish(pu): add LN and GN norm_type support in ResBlock
  ding/torch_utils/network/nn_module.py
  ding/torch_utils/network/normalization.py
  ding/torch_utils/network/res_block.py
  ding/torch_utils/network/tests/test_res_block.py
Labels: enhancement

#661 feature(nyz): add MAPPO/MASAC task example
  ding/example/mappo.py
  ding/example/masac.py
  ding/framework/middleware/functional/logger.py
  ding/framework/middleware/functional/trainer.py
  ding/framework/middleware/learner.py
  ding/policy/sac.py
  ding/torch_utils/network/nn_module.py
  dizoo/petting_zoo/config/ptz_simple_spread_masac_config.py
  dizoo/petting_zoo/envs/petting_zoo_simple_spread_env.py
  dizoo/petting_zoo/envs/test_petting_zoo_simple_spread_env.py
Labels: algo, config

#659 fix(zjow): update td3bc d4rl config
  dizoo/d4rl/config/halfcheetah_expert_td3bc_config.py
  dizoo/d4rl/config/halfcheetah_medium_expert_td3bc_config.py
  dizoo/d4rl/config/halfcheetah_medium_replay_td3bc_config.py
  dizoo/d4rl/config/halfcheetah_medium_td3bc_config.py
  dizoo/d4rl/config/halfcheetah_random_td3bc_config.py
  dizoo/d4rl/config/hopper_expert_td3bc_config.py
  dizoo/d4rl/config/hopper_medium_expert_td3bc_config.py
  dizoo/d4rl/config/hopper_medium_replay_td3bc_config.py
  dizoo/d4rl/config/hopper_medium_td3bc_config.py
  dizoo/d4rl/config/hopper_random_td3bc_config.py
  dizoo/d4rl/config/walker2d_expert_td3bc_config.py
  dizoo/d4rl/config/walker2d_medium_expert_td3bc_config.py
  dizoo/d4rl/config/walker2d_medium_replay_td3bc_config.py
  dizoo/d4rl/config/walker2d_medium_td3bc_config.py
  dizoo/d4rl/config/walker2d_random_td3bc_config.py
Labels: config

#662 fix(zp): add record_random_collect option
  ding/entry/utils.py
  ding/worker/collector/sample_serial_collector.py
  ding/worker/collector/tests/test_sample_serial_collector.py
Labels: enhancement

#640 feature(zc): add bcq algorithm
  ding/example/bcq.py
  ding/model/template/__init__.py
  ding/model/template/bcq.py
  ding/policy/__init__.py
  ding/policy/bcq.py
  ding/policy/command_mode_policy_instance.py
  dizoo/d4rl/config/halfcheetah_medium_bcq_config.py
  dizoo/d4rl/config/halfcheetah_medium_expert_bcq_config.py
  dizoo/d4rl/config/hopper_medium_bcq_config.py
  dizoo/d4rl/config/hopper_medium_expert_bcq_config.py
  dizoo/d4rl/entry/d4rl_bcq_main.py
Labels: algo

#672 polish(nyz): simplify requirements
  ding/framework/middleware/functional/logger.py
  ding/reward_model/pdeil_irl_model.py
  ding/utils/compression_helper.py
  ding/utils/data/dataset.py
  ding/world_model/ddppo.py
  setup.py
Labels: enhancement, test
