Repository opendilab/DI-engine, pull requests merged in 2023-06, with the labels that each got.

#674 Doc(zjow): Huggingface badge
  README.md
Labels: doc

#673 feature(cy): add tensor stream merging tools
  ding/torch_utils/network/__init__.py
  ding/torch_utils/network/merge.py
  ding/torch_utils/network/tests/test_merge.py
Labels: enhancement

#677 feature(cxy): add cliffwalking env
  README.md
  dizoo/cliffwalking/__init__.py
  dizoo/cliffwalking/cliff_walking.gif
  dizoo/cliffwalking/config/cliffwalking_dqn_config.py
  dizoo/cliffwalking/entry/cliffwalking_dqn_deploy.py
  dizoo/cliffwalking/entry/cliffwalking_dqn_main.py
  dizoo/cliffwalking/envs/__init__.py
  dizoo/cliffwalking/envs/cliffwalking_env.py
  dizoo/cliffwalking/envs/test_cliffwalking_env.py
Labels: env

#678 feature(nyz): fix py37 macos ci bug and update default pytorch to 1.12.1
  .github/workflows/platform_test.yml
  .github/workflows/unit_test.yml
  docker/Dockerfile.base
Labels: docker

#680 feature(yzj): add scatter connection model
  ding/torch_utils/network/scatter_connection.py
  ding/torch_utils/network/tests/test_scatter.py
Labels: algo
