Repository opendilab/DI-engine, pull requests merged in 2023-08, with the labels that each got.

#695 doc(zjow): update README.md with openxlab badge
  README.md
Labels: doc

#652 feature(zp): add dreamerv3 algorithm
  ding/entry/__init__.py
  ding/entry/serial_entry_mbrl.py
  ding/entry/utils.py
  ding/envs/env_wrappers/env_wrappers.py
  ding/model/common/encoder.py
  ding/model/common/tests/test_encoder.py
  ding/model/template/__init__.py
  ding/model/template/vac.py
  ding/policy/command_mode_policy_instance.py
  ding/policy/mbpolicy/__init__.py
  ding/policy/mbpolicy/dreamer.py
  ding/policy/mbpolicy/utils.py
  ding/torch_utils/network/__init__.py
  ding/torch_utils/network/dreamer.py
  ding/torch_utils/network/tests/test_dreamer.py
  ding/worker/collector/interaction_serial_evaluator.py
  ding/worker/collector/sample_serial_collector.py
  ding/worker/replay_buffer/__init__.py
  ding/worker/replay_buffer/naive_buffer.py
  ding/world_model/dreamer.py
  ding/world_model/model/__init__.py
  ding/world_model/model/networks.py
  ding/world_model/model/tests/test_networks.py
  ding/world_model/tests/test_dreamer.py
  dizoo/dmc2gym/config/cartpole_balance/cartpole_balance_dreamer_config.py
  dizoo/dmc2gym/config/cheetah_run/cheetah_run_dreamer_config.py
  dizoo/dmc2gym/config/dmc2gym_dreamer_config.py
  dizoo/dmc2gym/config/dmc2gym_sac_pixel_config.py
  dizoo/dmc2gym/config/walker_walk/walker_walk_dreamer_config.py
  dizoo/dmc2gym/envs/dmc2gym_env.py
Labels: algo

#696 feature(zjow): add middleware for ape-x structure pipeline
  ding/data/buffer/middleware/priority.py
  ding/data/buffer/tests/test_middleware.py
  ding/framework/middleware/__init__.py
  ding/framework/middleware/distributer.py
  ding/framework/middleware/functional/__init__.py
  ding/framework/middleware/functional/enhancer.py
  ding/framework/middleware/functional/priority.py
  ding/framework/middleware/learner.py
  ding/framework/middleware/tests/test_distributer.py
  ding/framework/middleware/tests/test_priority.py
  ding/policy/dqn.py
Labels: efficiency optimization, enhancement

#703 feature(pu): add three variants of Bilinear classes and a FiLM class
  ding/torch_utils/network/merge.py
  ding/torch_utils/tests/test_merge.py
Labels: enhancement, algo

#706 feature(whl): add example of dqn eval
  ding/example/dqn_eval.py
Labels: enhancement

#708 fix(lixuelin): to_ndarray fails to assign dtype for scalars
  ding/torch_utils/data_helper.py
Labels: bug

#711 fix(zjow): fix mujoco-py compatibility issue for cython<3
  docker/Dockerfile.env
Labels: bug, docker
