Repository opendilab/DI-engine, pull requests merged in 2023-01, with the labels that each got.

#565 fix(nyz): fix py38 unittest bugs
  ding/data/level_replay/level_sampler.py
  ding/envs/env_manager/tests/conftest.py
  ding/envs/env_manager/tests/test_base_env_manager.py
  ding/envs/env_manager/tests/test_env_supervisor.py
  ding/envs/env_manager/tests/test_gym_vector_env_manager.py
  ding/envs/env_manager/tests/test_subprocess_env_manager.py
  ding/framework/middleware/tests/test_logger.py
  ding/framework/task.py
  ding/torch_utils/loss/multi_logits_loss.py
  ding/torch_utils/loss/tests/test_contrastive_loss.py
  ding/worker/collector/tests/speed_test/test_collector_profile.py
Labels: bug

#563 feature(nyz): add new gym hybrid viz
  .gitignore
  ding/worker/collector/interaction_serial_evaluator.py
  dizoo/gym_hybrid/config/gym_hybrid_ddpg_config.py
  dizoo/gym_hybrid/config/gym_hybrid_hppo_config.py
  dizoo/gym_hybrid/config/gym_hybrid_mpdqn_config.py
  dizoo/gym_hybrid/config/gym_hybrid_pdqn_config.py
  dizoo/gym_hybrid/entry/gym_hybrid_ddpg_eval.py
  dizoo/gym_hybrid/envs/gym-hybrid/gym_hybrid/bg.jpg
  dizoo/gym_hybrid/envs/gym-hybrid/gym_hybrid/environments.py
  dizoo/gym_hybrid/envs/gym-hybrid/gym_hybrid/target.png
  dizoo/gym_hybrid/envs/gym_hybrid_env.py
  dizoo/gym_hybrid/moving_v0.gif
Labels: env

#558 feature(cy): add BDQ algorithm
  README.md
  ding/entry/tests/test_serial_entry.py
  ding/model/common/__init__.py
  ding/model/common/head.py
  ding/model/template/__init__.py
  ding/model/template/q_learning.py
  ding/model/template/tests/test_q_learning.py
  ding/policy/__init__.py
  ding/policy/bdq.py
  ding/policy/command_mode_policy_instance.py
  ding/rl_utils/__init__.py
  ding/rl_utils/td.py
  ding/rl_utils/tests/test_td.py
  dizoo/classic_control/pendulum/config/pendulum_bdq_config.py
  dizoo/mujoco/config/halfcheetah_bdq_config.py
  dizoo/mujoco/config/hopper_bdq_config.py
  dizoo/mujoco/envs/mujoco_env.py
Labels: algo, config

#567 feature(nyz): add PPOF new interface support
  ding/bonus/__init__.py
  ding/bonus/config.py
  ding/bonus/model.py
  ding/bonus/ppof.py
  ding/config/__init__.py
  ding/envs/env/ding_env_wrapper.py
  ding/envs/env_manager/subprocess_env_manager.py
  ding/framework/middleware/__init__.py
  ding/framework/middleware/ckpt_handler.py
  ding/framework/middleware/collector.py
  ding/framework/middleware/functional/__init__.py
  ding/framework/middleware/functional/advantage_estimator.py
  ding/framework/middleware/functional/collector.py
  ding/framework/middleware/functional/data_processor.py
  ding/framework/middleware/functional/evaluator.py
  ding/framework/middleware/functional/logger.py
  ding/framework/middleware/functional/trainer.py
  ding/framework/middleware/tests/test_ckpt_handler.py
  ding/framework/middleware/tests/test_collector.py
  ding/framework/middleware/tests/test_data_processor.py
  ding/framework/middleware/tests/test_logger.py
  ding/framework/middleware/tests/test_trainer.py
  ding/policy/__init__.py
  ding/policy/common_utils.py
  ding/policy/ppof.py
  ding/rl_utils/__init__.py
  ding/rl_utils/sampler.py
  dizoo/gym_pybullet_drones/envs/__init__.py
  dizoo/gym_pybullet_drones/envs/gym_pybullet_drones_env.py
  dizoo/rocket/README.md
  dizoo/rocket/envs/__init__.py
  dizoo/rocket/envs/rocket_env.py
  dizoo/rocket/envs/test_rocket_env.py
  setup.py
Labels: enhancement, algo

#568 polish(nyz): polish example demos
  ding/config/config.py
  ding/entry/serial_entry_preference_based_irl.py
  ding/entry/serial_entry_preference_based_irl_onpolicy.py
  ding/entry/tests/test_application_entry.py
  ding/entry/tests/test_application_entry_trex_collect_data.py
  ding/entry/tests/test_serial_entry.py
  ding/entry/tests/test_serial_entry_bc.py
  ding/entry/tests/test_serial_entry_preference_based_irl.py
  ding/entry/tests/test_serial_entry_preference_based_irl_onpolicy.py
  ding/entry/tests/test_serial_entry_reward_model.py
  ding/example/c51_nstep.py
  ding/example/collect_demo_data.py
  ding/example/cql.py
  ding/example/d4pg.py
  ding/example/ddpg.py
  ding/example/dqn.py
  ding/example/dqn_her.py
  ding/example/dqn_new_env.py
  ding/example/dqn_nstep.py
  ding/example/dqn_per.py
  ding/example/dqn_rnd.py
  ding/example/iqn_nstep.py
  ding/example/pdqn.py
  ding/example/ppg_offpolicy.py
  ding/example/ppo.py
  ding/example/ppo_offpolicy.py
  ding/example/qrdqn_nstep.py
  ding/example/r2d2.py
  ding/example/sac.py
  ding/example/sqil.py
  ding/example/sqil_continuous.py
  ding/example/sql.py
  ding/example/td3.py
  ding/example/trex.py
  ding/framework/middleware/ckpt_handler.py
  ding/framework/middleware/collector.py
  ding/framework/middleware/tests/test_ckpt_handler.py
  ding/reward_model/trex_reward_model.py
  dizoo/classic_control/cartpole/config/__init__.py
  dizoo/classic_control/cartpole/config/cartpole_c51_config.py
  dizoo/classic_control/cartpole/config/cartpole_dqn_config.py
  dizoo/classic_control/cartpole/config/cartpole_iqn_config.py
  dizoo/classic_control/cartpole/config/cartpole_ppo_offpolicy_config.py
  dizoo/classic_control/cartpole/config/cartpole_sqil_config.py
  dizoo/classic_control/cartpole/config/cartpole_trex_dqn_config.py
  dizoo/classic_control/pendulum/config/pendulum_sqil_sac_config.py
Labels: enhancement

#572 style(eltociear): fix typo in contrastive_loss.py
  ding/torch_utils/loss/contrastive_loss.py
Labels: typo
