Repository opendilab/DI-engine, pull requests merged in 2023-04, with the labels that each got.

#628 feature(wgt): add torch-rpc fix dockerfile
  .github/workflows/deploy.yml
  docker/Dockerfile.rpc
Labels: docker

#624 polish(gry) : polish reward model and td error
  ding/reward_model/drex_reward_model.py
  ding/reward_model/gail_irl_model.py
  ding/reward_model/guided_cost_reward_model.py
  ding/reward_model/icm_reward_model.py
  ding/reward_model/ngu_reward_model.py
  ding/reward_model/pdeil_irl_model.py
  ding/reward_model/pwil_irl_model.py
  ding/reward_model/red_irl_model.py
  ding/reward_model/rnd_reward_model.py
  ding/reward_model/trex_reward_model.py
  ding/rl_utils/td.py
Labels: enhancement

#625 feature(whl): add gpt utils
  ding/torch_utils/backend_helper.py
  ding/torch_utils/lr_scheduler.py
  ding/torch_utils/model_helper.py
  ding/torch_utils/network/activation.py
  ding/torch_utils/optimizer_helper.py
  ding/torch_utils/tests/test_backend_helper.py
  ding/torch_utils/tests/test_lr_scheduler.py
  ding/torch_utils/tests/test_model_helper.py
  ding/torch_utils/tests/test_optimizer.py
  ding/utils/data/collate_fn.py
Labels: enhancement, docker

#605 feature(lxy): add popart & value rescale & symlog to ppof
  ding/bonus/model.py
  ding/bonus/ppof.py
  ding/model/common/__init__.py
  ding/model/common/head.py
  ding/policy/ppof.py
  ding/rl_utils/__init__.py
  ding/rl_utils/tests/test_value_rescale.py
  ding/rl_utils/value_rescale.py
  ding/torch_utils/network/__init__.py
  ding/torch_utils/network/popart.py
  ding/torch_utils/network/tests/test_popart.py
Labels: algo

#641 fix(nyz): fix confusing shallow copy operation bug about next_obs
  ding/worker/collector/base_serial_collector.py
  ding/worker/collector/battle_episode_serial_collector.py
  ding/worker/collector/battle_sample_serial_collector.py
  ding/worker/collector/episode_serial_collector.py
  ding/worker/collector/sample_serial_collector.py
  ding/worker/collector/tests/test_base_serial_collector.py
Labels: bug

#570 feature(wgt): add barrier middleware
  .coveragerc
  ding/framework/middleware/__init__.py
  ding/framework/middleware/barrier.py
  ding/framework/middleware/tests/test_barrier.py
  ding/framework/parallel.py
  ding/framework/task.py
Labels: enhancement

#644 feature(zjow): add PPO demo for complex env observation
  ding/example/ppo_with_complex_obs.py
  ding/framework/middleware/functional/advantage_estimator.py
  ding/framework/middleware/functional/collector.py
  ding/framework/middleware/functional/trainer.py
  ding/torch_utils/data_helper.py
  ding/torch_utils/tests/test_data_helper.py
  ding/utils/default_helper.py
  ding/utils/tests/test_default_helper.py
Labels: algo

#653 fix(zjow): fix incompatible gym version bug in Dockerfile.env
  docker/Dockerfile.env
Labels: bug
