Repository opendilab/DI-engine, pull requests merged in 2023-10, with the labels that each got.

#724 doc(zjow): polish rl_utils doc
  ding/rl_utils/__init__.py
  ding/rl_utils/a2c.py
  ding/rl_utils/acer.py
  ding/rl_utils/adder.py
  ding/rl_utils/coma.py
  ding/rl_utils/exploration.py
  ding/rl_utils/gae.py
  ding/rl_utils/isw.py
  ding/rl_utils/ppg.py
  ding/rl_utils/ppo.py
  ding/rl_utils/retrace.py
  ding/rl_utils/sampler.py
  ding/rl_utils/td.py
  ding/rl_utils/upgo.py
  ding/rl_utils/vtrace.py
Labels: doc

#734 doc(whl): add code doc for LT,DT,PC,BC models
  ding/model/template/bc.py
  ding/model/template/decision_transformer.py
  ding/model/template/language_transformer.py
  ding/model/template/procedure_cloning.py
  ding/model/template/tests/test_procedure_cloning.py
Labels: doc

#735 feature(luyd): add collector logging in new pipeline
  ding/framework/middleware/functional/collector.py
Labels: enhancement

#736 polish(rjy): polish comments of qmix/pdqn/mavac
  ding/model/template/mavac.py
  ding/model/template/pdqn.py
  ding/model/template/qmix.py
Labels: doc

#737 env(zjow): add Huggingface model card support for ppof envs
  ding/bonus/config.py
  ding/bonus/ppof.py
Labels: config

#733 doc(zjow): update README.md and Colab demo
  README.md
Labels: doc

#738 doc(whl): polish doc for data_helper, model_helper, parameter, metric, math_helper, backend_helper
  ding/torch_utils/backend_helper.py
  ding/torch_utils/data_helper.py
  ding/torch_utils/math_helper.py
  ding/torch_utils/metric.py
  ding/torch_utils/model_helper.py
  ding/torch_utils/parameter.py
Labels: doc

#742 polish(pu): polish comments in env_wrappers.py and ding_env_wrapper.py
  ding/envs/env/ding_env_wrapper.py
  ding/envs/env_wrappers/env_wrappers.py
Labels: doc

#739 polish(rjy): polish comments in wqmix/ngu/pg model
  ding/model/template/ngu.py
  ding/model/template/pg.py
  ding/model/template/wqmix.py
Labels: doc

#732 polish(nyz): polish dqn and ppo comments
  ding/policy/__init__.py
  ding/policy/base_policy.py
  ding/policy/bc.py
  ding/policy/command_mode_policy_instance.py
  ding/policy/common_utils.py
  ding/policy/cql.py
  ding/policy/ddpg.py
  ding/policy/dqn.py
  ding/policy/dt.py
  ding/policy/impala.py
  ding/policy/mdqn.py
  ding/policy/pdqn.py
  ding/policy/policy_factory.py
  ding/policy/ppo.py
  ding/policy/qmix.py
  ding/policy/r2d2.py
  ding/policy/sac.py
  ding/policy/td3.py
  ding/policy/tests/test_cql.py
  ding/rl_utils/td.py
  dizoo/classic_control/cartpole/config/cartpole_cql_config.py
  dizoo/classic_control/cartpole/config/cartpole_sac_config.py
Labels: doc
