Repository opendilab/DI-engine, pull requests merged in 2024-01, with the labels that each got.

#717 feature(rjy): add HAPPO algorithm
  ding/model/common/head.py
  ding/model/template/__init__.py
  ding/model/template/havac.py
  ding/model/template/tests/test_havac.py
  ding/policy/__init__.py
  ding/policy/command_mode_policy_instance.py
  ding/policy/happo.py
  ding/rl_utils/__init__.py
  ding/rl_utils/happo.py
  ding/rl_utils/tests/test_happo.py
  dizoo/multiagent_mujoco/config/halfcheetah_happo_config.py
  dizoo/multiagent_mujoco/config/halfcheetah_mappo_config.py
  dizoo/multiagent_mujoco/config/walker2d_happo_config.py
  dizoo/petting_zoo/config/ptz_simple_spread_happo_config.py
Labels: algo

#762 doc(rjy): polish d4pg/ppg/qrdqn policy doc
  ding/policy/d4pg.py
  ding/policy/ppg.py
  ding/policy/qrdqn.py
Labels: doc

#768 polish(pu): polish comments in a2c/bcq/fqf/ibc policy
  ding/example/bcq.py
  ding/policy/a2c.py
  ding/policy/acer.py
  ding/policy/base_policy.py
  ding/policy/bcq.py
  ding/policy/ddpg.py
  ding/policy/dqn.py
  ding/policy/fqf.py
  ding/policy/ibc.py
Labels: config, doc

#764 polish(rjy): polish pg/iqn/edac policy doc
  ding/policy/edac.py
  ding/policy/iqn.py
  ding/policy/pg.py
Labels: doc
