Repository opendilab/DI-engine, pull requests merged in 2024-04, with the labels that each got.

#786 fix(zjow): fix complex obs demo for ppo pipeline
  .github/workflows/unit_test.yml
  ding/example/ppo_with_complex_obs.py
  ding/framework/middleware/functional/advantage_estimator.py
  ding/utils/__init__.py
  ding/utils/dict_helper.py
Labels: bug

#788 feature(nyz): add GPU utils
  ding/utils/__init__.py
  ding/utils/memory_helper.py
  ding/utils/tests/test_memory_helper.py
  setup.py
Labels: efficiency optimization

#782 env(rjy): add ising model env
  README.md
  ding/model/template/q_learning.py
  ding/policy/common_utils.py
  ding/rl_utils/adder.py
  ding/rl_utils/td.py
  dizoo/ising_env/__init__.py
  dizoo/ising_env/config/ising_mfq_config.py
  dizoo/ising_env/entry/ising_mfq_eval.py
  dizoo/ising_env/envs/__init__.py
  dizoo/ising_env/envs/ising_model/Ising.py
  dizoo/ising_env/envs/ising_model/__init__.py
  dizoo/ising_env/envs/ising_model/multiagent/__init__.py
  dizoo/ising_env/envs/ising_model/multiagent/core.py
  dizoo/ising_env/envs/ising_model/multiagent/environment.py
  dizoo/ising_env/envs/ising_model_env.py
  dizoo/ising_env/envs/test_ising_model_env.py
  dizoo/ising_env/ising_env.gif
Labels: env
